# Generated by Django 5.0.1 on 2024-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="用户名")),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "email",
                    models.CharField(max_length=100, null=True, verbose_name="邮箱"),
                ),
                (
                    "phone",
                    models.CharField(max_length=50, null=True, verbose_name="手机号"),
                ),
                ("begin", models.DateField(null=True, verbose_name="授权起始日期")),
                ("ende", models.DateField(null=True, verbose_name="授权终止日期")),
                (
                    "modelkey",
                    models.CharField(max_length=2048, null=True, verbose_name="大模型key"),
                ),
                ("isvalid", models.SmallIntegerField(default=1, verbose_name="是否有效")),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updatetime",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "account",
                "ordering": ("id",),
            },
        ),
    ]
