# Generated by Django 5.0.1 on 2024-01-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appaccounts", "0002_logmodel_rename_ende_accountmodel_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanmuModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="用户名")),
                ("danmuid", models.CharField(max_length=50, verbose_name="弹幕ID")),
                ("plat", models.CharField(max_length=20, null=True, verbose_name="平台")),
                ("type", models.CharField(max_length=20, null=True, verbose_name="类型")),
                (
                    "liveid",
                    models.CharField(max_length=30, null=True, verbose_name="直播间ID"),
                ),
                (
                    "danmu_userid",
                    models.CharField(max_length=30, null=True, verbose_name="弹幕用户ID"),
                ),
                (
                    "danmu_usernick",
                    models.CharField(max_length=30, null=True, verbose_name="弹幕用户昵称"),
                ),
                (
                    "danmu_usergender",
                    models.CharField(max_length=10, null=True, verbose_name="弹幕用户性别"),
                ),
                (
                    "content",
                    models.CharField(max_length=50, null=True, verbose_name="弹幕"),
                ),
                (
                    "reply",
                    models.CharField(max_length=50, null=True, verbose_name="回复弹幕"),
                ),
                (
                    "createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "danmu",
                "verbose_name_plural": "danmu",
                "ordering": ("id",),
            },
        ),
    ]
